### ISSUE TITLE
Markdown files are ignored

### ISSUE THREAD

**Issue by Travus** [Almighty-Alpaca/JetBrains-Discord-Integration#103]
Hello!

I noticed that the markdown files seem to be ignored. Whenever I am viewing or editing a markdown file the "Editing XXX.md" and small icon fields are not displayed, despite working for other file types. Is this intentional?

**Comment by Almighty-Alpaca** [comment]
No, this is a bug in the Markdown plugin. The split view editor reports `null` instead of the actual file being edited. As soon as you disable the plugin and use the "normal" editor it works as expected. I've already submitted a [PR to the intellij-community repo ](/JetBrains/intellij-community/pull/1373) but yet have to receive any response.

**Comment by Travus** [comment]
Ahh, Ok! Good to know, and thanks for the quick response!
Also, thanks for creating such an awesome tool!

**Comment by InfRandomness** [comment]
A pull request was made to the IntelliJ Idea repository but it has not been merged yet, you can find the pull request [there](https://github.com/JetBrains/intellij-community/pull/1373)

**Comment by Almighty-Alpaca** [comment]
Can confirm this finally works on the latest IntelliJ version 🎉
