### ISSUE TITLE
Webstorm not showing Rich Presence

### ISSUE THREAD

**Issue by BEDIRHANSAMSA** [Almighty-Alpaca/JetBrains-Discord-Integration#152]
Hi,

Rider is showing but Webstorm is not showing. I try force reconnect but not working.

![image](https://user-images.githubusercontent.com/44173331/113454273-895ea180-9410-11eb-8f5f-0b0f1a573ffe.png)

![image](https://user-images.githubusercontent.com/44173331/113454299-954a6380-9410-11eb-9a69-fc54d3478a7a.png)

**Comment by niels-bosman** [comment]
In the discord server from this repo there are some fixes for common problems, you could try these.

1) The plugin does not work with the web version of Discord
2) Open Settings > Other Settings > Discord and check for any big red error messages
3) Enable/Disable the Rich Presence once (Settings > Other Settings > Discord > Disable 'Show Rich Presence' > Apply > Enable 'Show Rich Presence' > Apply)
4) Due to Windows security features if you run Discord as administrator you also have to run your IDE as admin
5) When using Linux don't install Discord/IDE from the Software Center (Ubuntu) or as Snap Package, the packages are broken
6) Make sure in Discord Settings -> Game Activity -> Display running game as status message is checked
7) Make sure your IDE isn't added as a game in Discord
8) Check the IDE logs for any error messages involving this plugin. You can get to them by clicking Help > Show Log in Explorer and opening the idea.log file
9) Try starting Discord before starting the IDE
10) Try restarting both Discord and the IDE
11) Try reinstalling the plugin
12) Try restarting your PC

**Comment by BEDIRHANSAMSA** [comment]
I run IDE as admin and problem solved
