### ISSUE TITLE
[Suggestion] Different java files icons

### ISSUE THREAD

**Issue by Davoleo** [Almighty-Alpaca/JetBrains-Discord-Integration#45]
Just something to improve the rich presence in my opinion...
It would be nice to see different icon while editing different type of java files

for example the IntelliJ Class icon for Java normal classes, or the abstract classes IntelliJ icon for abstract classes, or interfaces IntelliJ icon when editing interfaces

I hope I explained myself well

**Comment by Almighty-Alpaca** [comment]
I get the idea but the problem is that I have to keep an eye on the amount of icons  because there's a limit of 150 perapplicaion. With a growing amount of languages I'm not sure I really want too add 5 icons per language.

I'll think about at it again when implementing the flat icon theme which I plan to do next although I'm not 100% sure when I'll get to that yet.

**Comment by Davoleo** [comment]
Oh, I see, I would really appreciate it, but if  it isn't possible then no problem
thanks anyway for thinking about it! :)

Also in my opinion IntelliJ isn't going to get more languages added, but I guess you're talking about JetBrains in general, right?
