### ISSUE TITLE
The version 1.2.0 is broken

### ISSUE THREAD

**Issue by FenikkusuKoneko** [Almighty-Alpaca/JetBrains-Discord-Integration#87]
The update of the status does not work at all.
Disabling showing the current project in the status does not work.
The elapsed time is not shown for the current project.
When I switch to other files it doesn't update.

I encountered this in JetBrains Rider 2020.1.0
Also tried in JetBrains IntelliJ IDEA 2020.1.1
OS: Windows 10

**Comment by Almighty-Alpaca** [comment]
The problem with the estimated time is known. It's currently broken due to some architectural changes that also affected the idle timeout, but I didn't have time to fix that before I wanted to release 2020.1 support.

You're the first one to report update issues though. Are there any error messages? Does `Tools > Discord > Force update now` fix the problem?

**Comment by FenikkusuKoneko** [comment]
No, the "Force update now" doesn't do anything.
Found some logs, maybe they help
https://hatebin.com/ddmynphulw

**Comment by Almighty-Alpaca** [comment]
Yeah they definitely help, thanks!

**Comment by Almighty-Alpaca** [comment]
v1.3.0 is now out and fixes a lot of bugs. Feel free to reopen or create a new one if you still experients this error.
